TEST_NET = False
ASSET_PAIR = "BTCBUSD"
ASSET_STABLE = "BUSD"
ASSET_COIN = "BTC"

if TEST_NET:
    BINANCE_API_KEY = "IwkSffbhbl4xvzav8kj5XcxBO1OC5u5nWkaCv0kZwPibfTjhrAW6zOiR3HXZXoRm"
    BINANCE_API_SEC = "1REVTYypRFWoWcf2vriifiEsHnb8cvk9SnCjfwSmNX3NuCccUTzCXdPQAlWQK8qC"
else:
    BINANCE_API_KEY = "yzKipyseCkuyoj88nHzMyN7OQCh3S2piE9fUxAG3Pav1U966afTTJVYfgpAPurdm"
    BINANCE_API_SEC = "1rclPeY0eXeUNxi6tNNM3BqHtCHwg1PDxAvl6hRKI5m2BVUl1j9D19A5C989uUU8"
